version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.78-jsonrpc-dev
    environment:
      - MODE=json-rpc
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://signal-cli-rest-api:8080/v1/health"]

  client:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      TZ: "Europe/Berlin"
      PHONE_NUMBER: "+49..."
    depends_on:
      signal-cli-rest-api:
        condition: service_healthy
